### ISSUE TITLE
Clone a node object

### ISSUE THREAD

**Issue by bocasfx** [bocasfx/q-react-canvas#2]
Implement the **cloneNode** function in _src/reducers/Nodes.js_ (line 134). This function should create a copy of an existing node object. The new node object should have a different id and a different (random) name.

The function should take two parameters:

- **state**: An array of node objects
- **id**: The id of the node object to be cloned

Expected result:

The function should return a **new** array consisting of all the nodes in the input array (state) plus the new cloned node.

**Branch from**: master

**Comment by bocasfx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clone a node object](https://trello.com/c/sWUfOYTW/1-clone-a-node-object)

**Comment by reallyrobkerr** [comment]
feature/QRC-002 has been merged
